# 1일차 학습 목표
- 파이썬 기본 자료구조
- 기본 문법
- 패키지 활용
- numpy, pandas 자료구조
- 데이터 처리 연습습

#1. 기본 자료구조

In [ ]:
list1 = [ 20,10,5]  #리스트
#실행: 플레이버튼, 또는  ctrl+enter
print( list1 )
list1[ 1 ]#인덱싱
list1[ 1:3 ] #슬라이싱
list1[ 2 ] = 40
list1[ 0 ] = "data"
list1.append( 1000000000 )
list1.append( list1 )

In [ ]:
tuple1 = ( 10,20,5 )
tuple1[1] = 40  #tuple의 값은은 수정 불가

In [ ]:
set1 = { 10,20, 5}
#set1[ 1 ]#인덱싱 불가
dict1 = {  'a':10,  'b':20,  'c':5}
dict1 #key-value
dict1['a']

10

In [ ]:
list3 = [ 3, 2.1, "A", 10]
list3[ 1:3 ]
list3[  2 ] = 100
list3.append( 99 )
list3

[3, 2.1, 100, 10, 99]

In [ ]:
list4 = [1,2,3]
list5 = [ [1,2], [3,4]    ]
list5

In [ ]:
dict2 = {'A':[1,2,3]  , 'B':[4,5,6] }
dict2

In [ ]:
list6 = [] 
list6.append( dict2 )
list6

[{'A': [1, 2, 3], 'B': [4, 5, 6]}]

#2. 조건문, 반복문, 예외처리 

In [ ]:
a = 90
a > 70

True

In [ ]:
if a > 70 :
  print("탕수육")

탕수육


In [ ]:
b=65
if b < 90 :
  if b <70:
    print("small")
  else:
    print("중간")
else:
  print("big")

small


In [ ]:
c=91
d=50
if (c > 90) | (d > 90):
  print("pizza")

pizza


In [ ]:
sales = [1,2,3,4,5]
for i in sales:
 if i > 3 :
  print(i)

# sales2 = [ 10, 7, 12, 5, 19, 6] 일때, sales2의 각 값이 10보다 작으면
# 2배해서 출력하고, 그렇지 않으면 그냥 출력하세요
sales2 = [ 10, 7, 12, 5, 19, 6]
for i in sales2:
  if i > 10:
    print(i*2)
  else:
    print(i)

#sales2의 값에다가 모두 2를 곱해서 출력하기
#방법1
for i in sales2:
  print( i*2 )
#방법2
[ i*2 for i in sales2   ]

#반복문+조건문 다르게 표현현
[ i*2 for i in sales2 if i >3  ]

# sales3 = [ 10, 11, 8, 9, 12]
# sales3의 값 중에서 10보다 작은 숫자들만 선택을해서,
# 5를 더해서 리스트로 만드세요
sales3 = [ 10, 11, 8, 9, 12]
[ i+5 for i in sales3 if i < 10  ]
#위와 같은 작업을 하는 ....
result = []
for i in sales3:
  if i < 10:
    result.append(i+5)

In [ ]:
list1 = [1.0,2.0,0.0,3.0,4.0]
for i in list1:
  try:
    print( 1/i)
  except:
    pass    #print("error")

1.0
0.5
0.3333333333333333
0.25


#3. numpy의 array 

In [ ]:
import numpy as np
ar1 = np.array( [1,2,3])
ar1*ar1 #행렬 계산 아님
np.matmul( ar1, ar1) #행렬 계산...
ar2 = np.array( [[1,2],[3,4]] )
ar2.shape
ar1.shape
ar3 = np.array(  [[[1,2],[3,4]],[[5,6],[7,8]]])
ar3.shape

(2, 2, 2)

- array생성 및 차원 확인

In [ ]:
import numpy as np
a = np.array( [0,1,2,3,4, 5.0])
a.shape #차원, 값의 개수
a.ndim
a.dtype #값의 종류, array->단일한 type의 값, 정수와 실수->실수 

array([0., 1., 2., 3., 4., 5.])

In [ ]:
a.reshape( (3,2)  ) #a가 변경되지는 않음

array([0., 1., 2., 3., 4., 5.])

In [ ]:
b = a.reshape((3,2))
print(b)
b.ndim
b.shape

In [ ]:
b.reshape( (6, )) #2->1D로 변경

array([0., 1., 2., 3., 4., 5.])

- array 연산과 인덱싱

In [ ]:
a[ [0,2,3] ]
b[  1  , 1     ]
b[ [0,2], 1]
b[ 0:2, 0]
b[ : , 0]  #1열만
b[  1 ,  :  ] #2행만

array([2., 3.])

In [ ]:
a > 3 
a[  [False, False, False, False,  True,  True] ]

a[   a>3   ] #3보다 큰 값만 출력
a[   a == 4 ]

print(b)
b[ b[:,1] >  3   ,  1 ] #2열의 값중에서 3보다 큰 값만 출력

#1열의 값 중에서 2이하인 값만 출력하고 10을 곱하세요
b[ b[:,0] <= 2,   0 ] * 10


[[0. 1.]
 [2. 3.]
 [4. 5.]]


array([ 0., 20.])

In [ ]:
#array 연산/인덱싱
a*2
a**2

[1,2,3,4,5]*2	#리스트와는 다름

#기본 인덱싱
a[ [2,3,4] ]
a[ np.array( [2,3,4]) ]	#인덱싱에 배열도 사용 가능

#논리 연산
a>4
a[ a>4 ]
a[ a>4 ] = 4



- 기본 활용 연습

In [ ]:
x = [0.0, 1, 2, 3, 4]
y = np.array(x)
y = np.array([[0.0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
np.shape(y)
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
np.shape(y)

x = [0, 1, 2, 3, 4] # Integers
y = np.array(x)
y.dtype

x = [0.0, 1, 2, 3, 4] # 0.0 is a float
y = np.array(x)
y.dtype

x = [0.0, 1, 2, 3, 4] # 하나라도 float이면 전체가 float임
y = np.array(x)
type(y)
y * y # Elementbyelement



array([ 0.,  1.,  4.,  9., 16.])

- 기본활용연습2: for 활용

In [ ]:
#array + for 같이 사용
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
for x in a: 
    print(x)

#array 값 접근하기
x = np.array([1.0,2.0,3.0,4.0,5.0])
x[0]

x = np.array([[1.0,2,3],[4,5,6]])
x[1,2]


[1. 2.]
[3. 4.]
[5. 6.]


6.0

- 인덱싱, 슬라이싱

In [ ]:
#슬라이싱
arr = np.arange(10, dtype=float).reshape((2, 5))
arr[0] # 0번째 원소
arr[0, 3] # 0행 3열
arr[0][3] # 0행3열

arr[0, :] # 0행, 1차원 배열
arr[:, 0] # 0열, 1차원 배열
arr[:, :2] # 첫 2개 열
arr[:, 2:] # 2 위치 이후 열
arr2 = arr[:, 1:4] # 위치1 과 위치4 사이 열
print(arr2)

#슬라이싱2
arr2 = arr[:, [1,2,3]] # arr 배열의 복사본
print(arr2)
arr2[0, 0] = 44
print(arr2)
print(arr)
arr2 = arr[arr > 5] # arr 배열의 복사본
print(arr2)
arr2[0] = 44
print(arr2)
print(arr)

arr[arr > 5] = 0
print(arr)



[[1. 2. 3.]
 [6. 7. 8.]]
[[1. 2. 3.]
 [6. 7. 8.]]
[[44.  2.  3.]
 [ 6.  7.  8.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[6. 7. 8. 9.]
[44.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


- numpy 활용 통계량 계산

In [ ]:
x = np.arange(10.0)	#0~9까지 10개 숫자를 갖는 자료구조 생성
x.mean()

np.mean(x)
x= np.reshape(np.arange(20.0),(4,5))
np.mean(x,0)

np.median(x)

np.std(x)
np.var(x)

33.25

- NaN 값의 처리

In [ ]:
import numpy as np
np.array( [ 1,2,np.NAN,4])
np.NAN # not a number

array([ 1.,  2., nan,  4.])

In [ ]:
#numpy.NAN:  숫자로 표현안되는 값
c = np.array( [1,2,np.NAN, 3,4])
c[  ~np.isnan(c) ]

array([1., 2., 3., 4.])

In [ ]:
#numpy.NAN:  숫자로 표현안되는 값
c = np.array( [1,2,np.NAN, 3,4])
np.isnan(c)
c[ ~np.isnan(c) ]

np.mean( c[~np.isnan(c) ])

#NaN 함수
x = np.random.randn(4)
x[1] = np.NaN
sum(x)
np.nansum(x)
sum(x[np.logical_not(np.isnan(x))])
np.nansum(x) / sum(np.isnan(x))



-1.3121040542561104

- 그 외 유용한 기능

In [ ]:
#max, amax, argmax, min, amin, argmin
x = np.random.randn(3,4)
np.amax(x)
x.max()
x.max(0)	#column별 계산
x.max(1) #row별 계산

data = np.genfromtxt('creditset2.csv',delimiter=',', skip_header=1)
np.mean(data,0)	#column방향
np.median(data, 0)
np.var(data, 0)
np.std(data, 0)

array([1.43227451e+04, 1.32591337e+01, 3.04464858e+03, 3.48536583e-01])

#4. pandas의 dataframe 

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series( [1,2,3], index=["r1","r2","r3"]   )
s1.index
s1.values
s2 = pd.Series( [1,2,3], index=["r3","r2","r1"]   )
s1+s2

df1=pd.DataFrame([[1,2],[3,4]],index=["r1","r2"],columns=["c1","c2"] )
df1.index # df1.columns #df1.values
#df1.info()
df1.describe()
df2=pd.DataFrame([[1,2], [3,4]],index=["r3","r2"],columns=["c3","c2"])
df1+df2
df1.columns=["c3", "c2"]


In [ ]:
#data.csv를 이용해서 data라는 데이터프레임 생성
import pandas as pd
data = pd.read_csv("data.csv")

#컬럼명을 확인
data.index
data.columns
data.values

#data.info()
data.shape
#2-3열, 10-110행 부분집합으로 출력(iloc)
data.iloc[ 9:110   , 1:3   ]

#두번째 컬럼을 3가지 방법으로 출력
data[  "X86" ]
data[  ["X86", "X87"] ]#2개 이상의 컬럼
data.iloc[ :, 1 ]
data.X86


0       2.3895
1       2.3754
2       2.4532
3       2.4004
4       2.4530
         ...  
1562    2.3762
1563    2.4880
1564    2.4590
1565    2.3600
1566    2.3701
Name: X86, Length: 1567, dtype: float64

- CSV 읽기 

In [ ]:
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_train.txt
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_test.txt

--2023-03-28 21:58:48--  https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt [following]
--2023-03-28 21:58:48--  https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14628807 (14M) [text/plain]
Saving to: ‘ratings_train.txt’

ratings_train.txt   100%[===================>]  13.95M  --.-KB/s    in 0.05s   



In [ ]:
import pandas as pd

train_df = pd.read_csv('ratings_train.txt', sep='\t')
train_df.head(3)
train_df['label'].value_counts( )

0    75173
1    74827
Name: label, dtype: int64

-apply 함수 활용 missing value 처리

In [ ]:
import numpy as np
import pandas as pd
def get_first_cabin(row):
	try:
		return row.split()[0]	#공백을 기준으로 나눈 첫번째 값
	except:
		return np.nan	
data = pd.read_csv("titanic_raw.csv")
data = data.replace('?', np.nan)	#치환
data['cabin'] = data['cabin'].apply(get_first_cabin) #cabin컬럼에 함수 적용용
data.head()
data.to_csv('titanic.csv', index=False)

- Category Encoding

In [ ]:
import random
import pandas as pd
import numpy as np

data = pd.read_csv('crx.data', header=None)
data.shape

varnames = ['A'+str(s) for s in range(1,17)]
data.columns = varnames
data = data.replace('?', np.nan)
data.info()

In [ ]:
#re-cast to float
data['A2'] = data['A2'].astype('float') #특정 컬럼의 type을 변환하는 메소드
data['A14'] = data['A14'].astype('float')

#re code target as binary
data['A16'] = data['A16'].map({'+':1, '-':0}) #딕셔너리 대로 값을 변환(키->밸류)

cat_cols = [c for c in data.columns if data[c].dtypes=='O']	#범주형 변수
num_cols = [c for c in data.columns if data[c].dtypes!='O']	#수치형 변수



In [ ]:
num_cols

['A2', 'A3', 'A8', 'A11', 'A14', 'A15', 'A16']

In [ ]:
#missing 처리
data[num_cols] = data[num_cols].fillna(0) #수치형변수만 선택->결측치->0으로 채우기기
data[cat_cols] = data[cat_cols].fillna('Missing')#범주형변수만 선택->결측치->Missing으로..

data.to_csv('creditApprovalUCI.csv', index=False) #행이름 제외하고 저장

- One Hot Encoding
 - onehot encoding 
 - 예: 성별->각 범주가 컬럼이 되고, 값은 1또는 0 또는 한 변수에서 값이 1과 0
 - 범주 수(k)-1개의 변수로 표현
 - 경우에 따라 범주 개수 만큼의 변수로 인코딩할 수 있음: 
 - DT와 같이 재귀적이고 분할하여 모델링하는 경우, 각 범주가 분리되는 것이 효과적

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

data = pd.read_csv('creditApprovalUCI.csv')

X_train, X_test, y_train, y_test = train_test_split(data.drop(labels=['A16'], axis=1), data['A16'], test_size=0.3,random_state=0)
X_train['A4'].unique()
X_train['A4'].isnull().mean()
X_train['A4'].value_counts()


u          363
y          115
Missing      4
l            1
Name: A4, dtype: int64

In [ ]:
tmp = pd.get_dummies( X_train['A4'], drop_first=False)#drop_first=True, OHE 할 때 컬럼을 줄여주는
tmp

In [ ]:
pd.get_dummies(X_train['A4'], drop_first=True)
tmp = pd.get_dummies(X_train['A4'], drop_first=True)	#k-1개로 인코딩
tmp.head()

In [ ]:
pd.get_dummies(X_train['A4'], drop_first=True, dummy_na=True)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


l  u  y  NaN
596  0  1  0    0
303  0  1  0    0
204  0  0  1    0
351  0  0  1    0
118  0  1  0    0
..  .. .. ..  ...
359  0  1  0    0
192  0  1  0    0
629  0  1  0    0
559  0  1  0    0
684  0  1  0    0

[483 rows x 4 columns]

- 연습
 - df0.csv, df1.csv를 각각 df, df2로 읽으세요

In [ ]:
import pandas as pd
df = pd.read_csv("df0.csv")
df2 = pd.read_csv("df1.csv")

In [ ]:
df2

date  value  change
0  2023-03-01   1000     1.5
1  2023-03-02   1010     1.3
2  2023-03-05   1008     0.9
3  2023-03-05   1011     1.5
4  2023-03-09   1000     1.5
5  2023-03-10   1010     1.3
6  2023-03-14   1008     0.9
7  2023-03-14   1011     1.5

In [ ]:
def func1( input):
  if input > 1:
    return 1
  else:
    return 0

df2["target"] = df2.change.apply(func1)
df2.target

0    1
1    1
2    0
3    1
4    1
5    1
6    0
7    1
Name: target, dtype: int64

In [ ]:
df["date2"] = df.date.str.replace(".","") #str은 필수 

<ipython-input-22-15e56b74a615>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["date2"] = df.date.str.replace(".","") #str은 생략가능능


In [ ]:
df2["date2"] = df2.date.str.replace("-","")

In [ ]:
df3 = pd.concat( [df,df2 ], axis=1) #컬럼 방향으로 추가, 옆으로...
print(df3)

In [ ]:

df4 = df3.groupby(['date2'])["value"].mean()

In [ ]:
#merge
df5 = pd.merge(df, df2, how="left", on="date2" )#왼쪽 데이터프레임(df)를 기준으로...
#두 데이터프레임의 공통적으로 있는 date2를 기준으로...
df5

In [ ]:
print(df5.dropna())#원본에 미적용
df5.dropna(inplace=True)#원본에 적용

In [ ]:
#df5에서 date2를 기준으로 value2의 평균을 group by
#df, df2를 merge할 때 , how="right"로 해보시고 결과를 df6 

In [ ]:
df5.groupby(['date2'])["value"].mean() #df5에서 date2기준, value컬럼의 평균

date2
20230301    10005.0
20230302    10103.0
20230305    10089.0
20230309    10005.0
20230310    10103.0
20230314    10115.0
Name: value2, dtype: float64

In [ ]:
pd.merge( df2, df, how="left", on="date2")

date_x  value  change  target     date2      date_y  value2
0  2023-03-01   1000     1.5       1  20230301  2023.03.01   10005
1  2023-03-02   1010     1.3       1  20230302  2023.03.02   10103
2  2023-03-05   1008     0.9       0  20230305  2023.03.05   10089
3  2023-03-05   1011     1.5       1  20230305  2023.03.05   10089
4  2023-03-09   1000     1.5       1  20230309  2023.03.09   10005
5  2023-03-10   1010     1.3       1  20230310  2023.03.10   10103
6  2023-03-14   1008     0.9       0  20230314  2023.03.14   10115
7  2023-03-14   1011     1.5       1  20230314  2023.03.14   10115

# Date, time 실습

- Dates, Time 변수 

In [ ]:
import pandas as pd
pd.date_range(start='1/1/2018', end='1/08/2018')
pd.date_range(start='2018-01-01', end='1/08/2018')
pd.date_range('2019-03-05', periods=20, freq='D')
pd.date_range('2019-03-05', periods=20, freq='3M')
pd.date_range('2019-03-05', periods=20, freq='3M')
pd.date_range('2019-03-05', periods=20, freq='T')#Time간격
pd.date_range('2019-03-05', periods=20, freq='3H')

In [ ]:
rng_ = pd.date_range('2019-03-05', periods=20, freq='T')
type(rng_)
df = pd.DataFrame({'date': rng_})
df.head()
df.shape
df.dtypes
df["date"].dt.date
df["date"].dt.time

In [ ]:
df['date'].dt.time
df['date_part'] = df['date'].dt.date
df['date_part'].head()

df['time_part'] = df['date'].dt.time
df['time_part'].head()

In [ ]:
df = pd.DataFrame({'date_var':['Jan-2015', 'Apr-2013', 'Jun-2014','Jan-2015']})
pd.to_datetime(df['date_var'])
df['datetime_var'] = pd.to_datetime(df['date_var'])

In [ ]:
df['date'] = df['datetime_var'].dt.date
df['time'] = df['datetime_var'].dt.time
df

date_var datetime_var        date      time
0  Jan-2015   2015-01-01  2015-01-01  00:00:00
1  Apr-2013   2013-04-01  2013-04-01  00:00:00
2  Jun-2014   2014-06-01  2014-06-01  00:00:00
3  Jan-2015   2015-01-01  2015-01-01  00:00:00

In [ ]:
#달과 연도 표시
import numpy as np
import pandas as pd
rng_ = pd.date_range('2019-03-05', periods=20, freq='M')
df = pd.DataFrame({'date': rng_})
df.head()
df['year'] = df['date'].dt.year
df.head()
df['month'] = df['date'].dt.month
df.head()
df['day'] = df['date'].dt.day
df.head()
df['quarter'] = df['date'].dt.quarter
df.head()

In [ ]:
np.where(df['quarter'].isin([1,2]), "1학기", "2학기") 

In [ ]:
df['semester'] = np.where(df['quarter'].isin([1,2]), 1, 2)  #np의 if 기능능
df.head()

In [ ]:
#day week표현
import numpy as np
import pandas as pd
rng_ = pd.date_range('2019-03-05', periods=20, freq='D')
df = pd.DataFrame({'date': rng_})
df.head()
df['day_mo'] = df['date'].dt.day
df.head()

df['day_week'] = df['date'].dt.dayofweek#월요일 0부터 시작.
df
df['day_week'].unique()

array([1, 2, 3, 4, 5, 6, 0])

In [ ]:
df['week'] = df['date'].dt.week
df.head()

In [ ]:
#datetime에서 time 추출
import numpy as np
import pandas as pd

rng_ = pd.date_range('2019-03-05', periods=20, freq='1h15min10s')
df = pd.DataFrame({'date': rng_})
df.head()
df['hour'] = df['date'].dt.hour
df['min'] = df['date'].dt.minute
df['sec'] = df['date'].dt.second
df.head()
df.info()

In [ ]:
df[['h','m','s']] = pd.DataFrame(
    [   (x.hour, x.minute, x.second)    for x in df['date']]#한개씩..
)
df.head()
#to_datetime()를 사용하면 object에서 datetime으로 변환
df['is_morning'] = np.where( (df['hour'] < 12) & (df['hour'] > 6), 
                            1, 0 )
df.head()


In [ ]:
#datetime 변수간 측정된 기간 표현
import datetime
import numpy as np
import pandas as pd

rng_hr = pd.date_range('2019-03-05', periods=20, freq='H')
rng_month = pd.date_range('2019-03-05', periods=20, freq='M')
df = pd.DataFrame({'date1': rng_hr, 'date2': rng_month})
df.head()
df['elapsed_days'] = (df['date2'] - df['date1']).dt.days
df.head(2)

date1      date2  elapsed_days
0 2019-03-05 00:00:00 2019-03-31            26
1 2019-03-05 01:00:00 2019-04-30            55

In [ ]:
df['months_passed'] = ((df['date2'] - df['date1']) / np.timedelta64(1, 'M')) #시간 간격, 월
df['months_passed'] = np.round(df['months_passed'],0) #반올림림
df.head()

df['diff_seconds'] = (df['date2'] - df['date1'])/np.timedelta64(1,'s')  #시간 간격, 초
df['diff_minutes'] = (df['date2'] - df['date1'])/np.timedelta64(1,'m')  #시간 간격, 분
df.head()

In [ ]:
df['to_today'] = (datetime.datetime.today() - df['date1'])  #오늘까지의 시간
df.head()